ACTIVE_BORDER="rgba(5e81acff)"
INACTIVE_BORDER="rgba(3b4252ff)"
WB_BG="#2e3440"
WB_FG="#d8dee9"
WB_ACCENT="#5e81ac"
WB_HOVER="#3b4252"
WB_ACTIVE_FG="#eceff4"
WB_TOOLTIP_BORDER="#4c566a"
WB_WARN="#ebcb8b"
WB_CRIT="#bf616a"

ROFI_BG="#2e3440"
ROFI_FG="#d8dee9"
ROFI_FG_DIM="#3b4252"
ROFI_BORDER="#5e81ac"
ROFI_SELECTED_FG="#eceff4"
